required=[
  "github.com/alecthomas/gometalinter",
  "github.com/client9/misspell/cmd/misspell",
  "github.com/go-swagger/go-swagger/cmd/swagger",
  "github.com/golang/lint/golint",
  "github.com/gordonklaus/ineffassign",
  "github.com/tsenart/deadcode",
  "honnef.co/go/tools/cmd/gosimple",
]

[[constraint]]
  name = "github.com/sirupsen/logrus"

[[constraint]]
  name = "github.com/go-openapi/errors"

[[constraint]]
  name = "github.com/go-openapi/runtime"

[[constraint]]
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  name = "github.com/go-openapi/swag"

[[constraint]]
  name = "github.com/go-openapi/validate"

[[constraint]]
  name = "github.com/go-zoo/bone"
  version = "1.2.0"

[[constraint]]
  name = "github.com/manifoldco/go-base32"

[[constraint]]
  name = "github.com/manifoldco/go-base64"
  version = "1.0.0"

[[constraint]]
  name = "github.com/manifoldco/go-connector"

[[constraint]]
  name = "github.com/manifoldco/go-jwt"

[[constraint]]
  name = "github.com/manifoldco/go-manifold"
  revision = "ca80cfb5bcc161b053f063e30a0d97c49fba1cc9"

[[constraint]]
  name = "github.com/manifoldco/go-signature"
  version = "1.0.0"

[[constraint]]
  name = "github.com/manifoldco/promptui"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.1.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.19.1"

[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/net"
