required=[
  "github.com/alecthomas/gometalinter",
  "github.com/client9/misspell/cmd/misspell",
  "github.com/go-swagger/go-swagger/cmd/swagger",
  "golang.org/x/lint/golint",
  "github.com/gordonklaus/ineffassign",
  "github.com/tsenart/deadcode",
  "honnef.co/go/tools/cmd/gosimple",
]

[[constraint]]
  name = "github.com/sirupsen/logrus"

[[constraint]]
  name = "github.com/go-openapi/errors"

[[constraint]]
  name = "github.com/go-openapi/runtime"

[[constraint]]
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  name = "github.com/go-openapi/swag"

[[constraint]]
  name = "github.com/go-openapi/validate"

[[constraint]]
  name = "github.com/go-zoo/bone"
  version = "1.2.0"

[[constraint]]
  name = "github.com/manifoldco/go-base32"
  version = "1.0.3"

[[constraint]]
  name = "github.com/manifoldco/go-base64"
  version = "1.0.2"

[[constraint]]
  name = "github.com/manifoldco/go-connector"
  version = "0.0.3"

[[constraint]]
  name = "github.com/manifoldco/go-jwt"
  version = "0.1.2"

[[constraint]]
  name = "github.com/manifoldco/go-manifold"
  version = "0.10.11"

[[constraint]]
  name = "github.com/manifoldco/go-signature"
  version = "1.0.2"

[[constraint]]
  name = "github.com/manifoldco/promptui"
  branch = "master"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.1.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.19.1"

[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/gobuffalo/packr"
